# This is the workflow to make and push wheels to PyPi

name: Build Wheels
on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'example/*'
      - '.github/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Branch Name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: github_info

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.github_info.outputs.branch }}

      - name: Build wheel
        run: python3 -m pip wheel . --no-deps --wheel-dir wheels

      - uses: actions/upload-artifact@v3
        with:
          name: pytgcalls-wheel
          path: ./wheels/py_tgcalls*.whl
          if-no-files-found: error

      - name: Publish a Python distribution to PyPI.
        if: github.ref == 'refs/heads/master' && github.repository == 'pytgcalls/ntgcalls'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: wheels/
